import React from 'react'

function Dashboard() {
  return (
    <>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eum consequuntur inventore ea minima excepturi omnis, suscipit soluta aliquid illo culpa molestiae illum modi deserunt quo aperiam corporis, reiciendis magni voluptatibus quas doloribus fugit deleniti vitae. Deserunt exercitationem in explicabo. Nulla reiciendis voluptate natus ullam qui labore animi sunt sapiente!</p>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Cum distinctio exercitationem error fugit. Eveniet officia non repudiandae adipisci enim beatae doloremque vero laborum sint asperiores, odit nobis repellat in modi, rem hic quibusdam sed explicabo repellendus ullam maxime quasi deleniti optio? Labore dolores veniam error sint aliquam vero quas consectetur, ipsa optio autem minima sunt asperiores explicabo, laboriosam dolore officiis magni! Quaerat quo officiis quam eligendi itaque qui, illum esse nemo eveniet, quia corrupti excepturi, ipsa voluptate nisi provident rerum quas recusandae repellendus dolores aperiam. Porro voluptates cumque perspiciatis, officia asperiores aperiam neque dignissimos autem. Nemo molestiae perferendis iusto aspernatur doloribus. Placeat laudantium beatae quia, quae debitis id iure, fugiat quas quod similique eum harum illo! Sunt laborum quod blanditiis voluptatem atque praesentium harum. Tempora, amet qui eius labore voluptate beatae blanditiis eaque nulla suscipit dolore minima, commodi error pariatur rem iusto nemo magnam! Voluptatem quia doloribus a illum nemo iure vero similique, eveniet totam qui blanditiis tempora deleniti pariatur magnam debitis quas delectus repellendus. Quae pariatur doloremque sapiente officiis quia minima deserunt ipsum! Iusto quis recusandae provident aliquam in neque adipisci fugit iure a? Alias aperiam voluptate excepturi, optio nemo laboriosam magni atque quas corporis voluptatem sint iste maiores doloremque dicta ratione maxime ab voluptatibus aliquid facere blanditiis culpa minima sunt et ipsa? Omnis ab consequuntur neque. Maiores, quibusdam quo incidunt aliquam laborum similique dolorem blanditiis iste nostrum, beatae adipisci, officia ex. Et consequuntur fugiat necessitatibus hic vero voluptates odit distinctio maiores quisquam sit modi vitae eos, numquam dignissimos ducimus nulla aspernatur ea. Molestias possimus laborum tempora explicabo debitis aut fuga adipisci! Facilis at sunt quae inventore blanditiis eum sit quas mollitia rem sint? Assumenda, eos corrupti nemo unde harum cumque dolores itaque hic. Aliquid suscipit ad est fuga veritatis maxime molestias praesentium ipsum placeat, repudiandae voluptate laborum doloremque laboriosam. Cumque ab culpa beatae est velit unde magni similique nobis totam natus sapiente, doloribus quod, cupiditate autem temporibus praesentium inventore, cum quas. Quis quae officia dolorem et praesentium totam facere deleniti adipisci, aperiam sapiente commodi consequatur, libero officiis nesciunt. Natus sint qui et ipsam sequi nulla. Suscipit quam, saepe, in consequuntur mollitia nesciunt eaque quidem ratione obcaecati facere debitis ab earum voluptatum inventore aliquam aliquid corrupti cumque beatae quibusdam cum voluptate magnam nihil ipsum quas? Officiis consequatur veritatis quasi ipsam! Deserunt sint quod inventore recusandae earum excepturi amet ipsa, quaerat suscipit reprehenderit ad fugiat cumque minus nemo facilis alias?</p>
    </>
  )
}

export default Dashboard